### ISSUE TITLE
本地测试正常，但是上传到GitHub空白

### ISSUE THREAD

**Issue by slzzz** [lazzzis/hexo-theme-only#3]
只可以看到title，页面是空的

**Comment by lazzzis** [comment]
生成的是这个项目吧: [Linux-2017/NewBlog](https://github.com/Linux-2017/NewBlog)
能否提供一下博客的地址?

**Comment by slzzz** [comment]
https://linux-2017.github.io/NewBlog/

2017-12-10 10:31 GMT+08:00 lazzzis <notifications@github.com>:

**Comment by slzzz** [comment]
有些css 是404 好像还在用以前的路径

2017-12-10 11:08 GMT+08:00 Haowee Shen <iamaluser2016@gmail.com>:

**Comment by lazzzis** [comment]
猜测可能是 _config.yml 中的 root 和 URL 问题。因为你生成的文件并不是在根目录 `/` 下，而是在子目录`/NewBlog`下，把
```yml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://linux-2017.github.io
root: /
```
改成
```yml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://linux-2017.github.io/NewBlog
root: /NewBlog/
```
试试
